### ISSUE TITLE
How to access/get serviceProviderId after login

### ISSUE THREAD

**Issue by xciser77** [lukebeer/broadworks-ocip#15]
After login I like to get the serviceProviderID because it is needed for some/many request.
I can find the spid after login with $client->getResponse(), but it is protected so i cannot get the value.

How can I get the serviceproviderid after login ?
Code I use is:
        $client = Factory::getSOAPClient('serveradres);
        $client->login('username','password');
        
        $connectinfo = $client->getResponse();

In the above code I removed the server/username/password

**Comment by andyrav** [comment]
You will need to do a UserGetLoginInfoRequest, then in then UserGetLoginInfoResponse will return
<xs:element name="loginType" type=" LoginType "/>
<xs:element name="locale" type=" OCILocale "/>
<xs:element name="encoding" type=" Encoding "/>
<xs:element name="groupId" type=" GroupId " minOccurs="0"/>
<xs:element name="serviceProviderId" type=" ServiceProviderId " minOccurs="0"/>
<xs:element name="isEnterprise" type=" xs:boolean "/>
<xs:element name="passwordExpiresDays" type=" xs:int " minOccurs="0"/>
<xs:element name="lastName" type=" LastName " minOccurs="0"/>
<xs:element name="firstName" type=" FirstName " minOccurs="0"/>
<xs:element name="userId" type=" UserId "/>
<xs:element name="phoneNumber" type=" DN " minOccurs="0"/>

**Comment by lukebeer** [comment]
```$serviceProviderId``` will be the service provider ID result or null.

```PHP
<?php
require_once 'vendor/autoload.php';

use BroadworksOCIP\api\Rel_17_sp4_1_197_OCISchemaAS\OCISchemaLogin\UserGetLoginInfoRequest;

$client = BroadworksOCIP\Factory::getSOAPClient('ocip.example.com');
if ($client->login('user', 'pass')) {
    $request = new UserGetLoginInfoRequest();
    $serviceProviderId = $request->get($client)->getServiceProviderId();
    $client->logout();
}
?>
```

**Comment by lukebeer** [comment]
```$serviceProviderId``` will be the service provider ID result or null.

```PHP
<?php
require_once 'vendor/autoload.php';

use BroadworksOCIP\api\Rel_17_sp4_1_197_OCISchemaAS\OCISchemaLogin\UserGetLoginInfoRequest;

$client = BroadworksOCIP\Factory::getSOAPClient('ocip.example.com');
if ($client->login('user', 'pass')) {
    $request = new UserGetLoginInfoRequest();
    $serviceProviderId = $request->get($client)->getServiceProviderId();
    $client->logout();
}
?>
```

**Comment by lukebeer** [comment]
```$serviceProviderId``` will be the service provider ID result or null.

```PHP
<?php
require_once 'vendor/autoload.php';

use BroadworksOCIP\api\Rel_17_sp4_1_197_OCISchemaAS\OCISchemaLogin\UserGetLoginInfoRequest;

$client = BroadworksOCIP\Factory::getSOAPClient('ocip.example.com');
if ($client->login('user', 'pass')) {
    $request = new UserGetLoginInfoRequest();
    $serviceProviderId = $request->get($client)->getServiceProviderId();
    $client->logout();
}
?>
```
